name: ✨Resource Suggestion
description: Suggest adding a resource to the Knowledge Hub.
title: "[RESOURCE] <descriptive title>"
labels:
  - suggestion/resource
body:
  - type: markdown
    attributes:
      value: >+
        Suggest an online resource to add to the Knowledge Hub. This resource
        can be anything directly (or indirectly) related to the climate
        movement. Have a few resources to suggest? Then submit multiple
        of these forms or, for many resources, use the "Resource Onboarding"
        form instead.


        Strict guidelines:

        - All resources must be legal (e.g. no linking to SciHub, Libgen, or any
        other resources that infringe on  copyright of research or books)



        Other considerations:

        - Try suggest resources that are "timeless", and not going to quickly go
        out of date.

        - Avoid linking of specific articles, or YouTube videos (unless they are
        particularly iconic/important)

        - **Title, tags, and resource summary data are used directly in the website**.
        Ensure to follow guidelines provided here in the form. Resource summary should be
        plain text (no markdown formatting or links). Include additional info in
        Relevance/Other comments field if appropriate.


        We will be somewhat liberal with including resources, prioritising
        making many resources available in an easily filterable way.

  - type: input
    attributes:
      label: Resource title
      description: Give an appropriate title for the resource ([<50 characters](https://wordcounter.net/character-count))
  - type: input
    attributes:
      label: URL
      description: URL to the resource
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant tags (1 per line)
      description: >-
        What tags would you like to apply to this resource? Leave blank if you're not
        sure and our mods will help out. Try use existing tags from the website,
        or applying one you feel is necessary. See a full list of existing tags
        [here](https://github.com/ClimateTown/knowledge-hub/blob/main/data/resource_tags.yml).
  - type: textarea
    attributes:
      label: Resource Summary
      description: >-
        Provide a summary of the resource ([<300 characters](https://wordcounter.net/character-count)). This will be displayed on
        the website alongside the title. Normally websites have an `og:description`
        tag in their HTML which you can go off (open "Inspect Element" in your browser
        and look for the tag).
  - type: textarea
    attributes:
      label: Relevance
      description: >-
        How is this resource relevant to the climate movement, or the
        ClimateTown community? Leave blank if already clear/self
        explanatory from other info. This field is only used for
        discussion in the onboarding process.
  - type: textarea
    attributes:
      label: Other comments
      description: Add any additional info you see fit.
