name: GitHub Discord Integration
on:
  issues:
    types:
      - opened
jobs:
  send-message:
    env:
      ISSUE_TITLE: ${{ github.event.issue.title }}
      ISSUE_DESCRIPTION: ${{ github.event.issue.body }}
      ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
      - name: Install dependencies
        run: |
          uv sync
      - name: Send message to Discord channel
        run: |
          uv run scripts/discord_integration.py \
            --webhook-url "${{ secrets.DISCORD_WEBHOOK }}" \
            --issue-number "${{ github.event.issue.number }}" \
            --issue-title "$ISSUE_TITLE" \
            --issue-description "$ISSUE_DESCRIPTION" \
            --author "$ISSUE_AUTHOR"
